name: CI

on: [push]

jobs:
    tests:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Setup TexLive and Friends
              run: |
                sudo apt-get update
                sudo apt-get install -y texlive texlive-fonts-extra texlive-latex-extra texlive-lang-cyrillic biber
            - name: Update 'texmf.cnf' settings
              shell: bash
              run: |
                sudo tee -a $(kpsewhich texmf.cnf) << EOF

                max_in_open = 50        % simultaneous input files and error insertions, 
                param_size = 20000      % simultaneous macro parameters, also applies to MP
                nest_size = 1000        % simultaneous semantic levels (e.g., groups)
                stack_size = 10000      % simultaneous input sources
                main_memory = 12000000
                EOF
                cat $(kpsewhich texmf.cnf)
                sudo fmtutil-sys --all
            - name: Run Tests
              shell: bash
              run: |
                export BIBINPUTS=`pwd`/lib/bib
                export STEXDIR=`pwd`
                export TEXINPUTS=.//:`pwd`/sty//:$TEXINPUTS
                make test -B
